In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import pandas as pd
import seaborn as sns

In [4]:
df = pd.read_csv("./data/Training_Data_0611N.csv")
df.head()

,cust_id,profitable_flag,count_accts,cm_age,flag_top_ed_spender,flag_cust_fee_paid_6m,pre6m_cust_spend,pre6m_cust_roc_cnt,pre6m_cust_non_disc_amt,pre6m_cust_non_disc_cnt,...,cnsumr_chrg_actv_cust_cnt,cnsumr_chrg_avg_credit_12m_amt,cnsumr_lend_actv_cust_cnt,cnsumr_lend_tot_util_ratio,sow_revol_avg_paydown_pct,sow_tot_annual_ext_pmt_amt,sow_tot_revol_bal_amt,sow_tot_revol_cnt,sow_tot_trans_bal_amt,sow_tot_trans_cnt
0,550391.0,0.0,1.0,74.0,1.0,0.0,"1,518",122.0,811,96.0,...,0.0,-,1.0,0.034044,0.0000,991,-,0.0,-,3.0
1,550392.0,0.0,1.0,64.0,0.0,0.0,"4,807",354.0,"1,052",82.0,...,0.0,7,1.0,0.044086,0.0877,2,24,2.0,-,0.0
2,550393.0,0.0,1.0,75.0,1.0,0.0,"2,361",204.0,"1,351",118.0,...,0.0,-,1.0,0.039613,0.0000,"4,828",-,0.0,387,3.0
3,550394.0,0.0,2.0,73.0,0.0,1.0,"5,452",142.0,"1,195",50.0,...,1.0,493,1.0,0.001200,0.0000,"4,598",-,0.0,295,4.0
4,550395.0,0.0,2.0,68.0,0.0,0.0,170,34.0,88,20.0,...,0.0,-,2.0,0.003378,0.0168,"2,176","2,606",5.0,143,13.0

In [5]:
df.describe()

,cust_id,profitable_flag,count_accts,cm_age,flag_top_ed_spender,flag_cust_fee_paid_6m,pre6m_cust_roc_cnt,pre6m_cust_non_disc_cnt,pre6m_cust_disc_cnt,pre6m_cust_online_cnt,...,self_accts,Customer Low Quality indicator,cdss_most_rcnt_prob,cbr_3_score,cnsumr_chrg_actv_cust_cnt,cnsumr_lend_actv_cust_cnt,cnsumr_lend_tot_util_ratio,sow_revol_avg_paydown_pct,sow_tot_revol_cnt,sow_tot_trans_cnt
count,19595.000000,19595.000000,19595.000000,19595.000000,19547.000000,19595.000000,19595.000000,19595.000000,19595.000000,19595.000000,...,19359.000000,19359.000000,19350.000000,19350.000000,19350.000000,19350.000000,19350.000000,19350.000000,19350.000000,19350.000000
mean,560188.000000,0.185966,1.227558,42.700128,0.530874,0.242103,448.679765,142.604134,306.075632,247.239398,...,0.029185,0.008781,0.007338,1185.215659,0.158966,1.057416,0.133133,0.016669,0.433902,0.787339
std,5656.733598,0.389089,0.515668,11.588827,0.499059,0.428367,531.939134,136.466289,465.602922,762.833133,...,0.270508,0.093299,0.042707,240.646855,0.373485,0.514165,0.217536,0.059165,1.082492,1.187996
min,550391.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-5.540188,0.000000,0.000000,0.000000
25%,555289.500000,0.000000,1.000000,34.000000,0.000000,0.000000,126.000000,34.000000,72.000000,48.000000,...,0.000000,0.000000,0.000000,1118.000000,0.000000,1.000000,0.003551,0.000000,0.000000,0.000000
50%,560188.000000,0.000000,1.000000,39.000000,1.000000,0.000000,348.000000,108.000000,210.000000,156.000000,...,0.000000,0.000000,0.000000,1262.000000,0.000000,1.000000,0.054909,0.000000,0.000000,0.000000
75%,565086.500000,0.000000,1.000000,48.000000,1.000000,0.000000,666.000000,214.000000,444.000000,336.000000,...,0.000000,0.000000,0.001000,1331.000000,0.000000,1.000000,0.157450,0.000000,0.000000,2.000000
max,569985.000000,1.000000,6.000000,99.000000,1.000000,1.000000,49264.000000,1260.000000,49264.000000,98504.000000,...,11.000000,1.000000,0.997000,1422.000000,2.000000,5.000000,4.718893,0.498500,10.000000,13.000000