In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import pandas as pd
import seaborn as sns

pd.set_option('display.max_columns', 500)
pd.set_option('max_colwidth', 800)

In [3]:
df = pd.read_csv("./data/Training_Data_0611N.csv")
df.head()
df.shape

,cust_id,profitable_flag,count_accts,cm_age,flag_top_ed_spender,flag_cust_fee_paid_6m,pre6m_cust_spend,pre6m_cust_roc_cnt,pre6m_cust_non_disc_amt,pre6m_cust_non_disc_cnt,pre6m_cust_disc_amt,pre6m_cust_disc_cnt,pre6m_cust_outbound_amt,pre6m_cust_online_amt,pre6m_cust_online_cnt,pre6m_cust_travel_amt,pre6m_cust_travel_cnt,pre6m_cust_retail_amt,pre6m_cust_retail_cnt,pre6m_cust_myca_active,pre6m_cust_mob_logins,pre6m_total_mc_trs,acq_sub_chn,acq_type_grp,fee_type_grp,Cust_tenure,pre6m_spend_active_ind,highly_utilized_ind,min_pay_ind,paid_in_full_ind,sum_total_line_amt,direct_debit_ind,referrals,spillover,self_accts,Customer Low Quality indicator,cdss_most_rcnt_prob,cust_max_credit_12m_amt,cust_max_remit_12m_amt,cbr_3_score,cnsumr_chrg_actv_cust_cnt,cnsumr_chrg_avg_credit_12m_amt,cnsumr_lend_actv_cust_cnt,cnsumr_lend_tot_util_ratio,sow_revol_avg_paydown_pct,sow_tot_annual_ext_pmt_amt,sow_tot_revol_bal_amt,sow_tot_revol_cnt,sow_tot_trans_bal_amt,sow_tot_trans_cnt
0,550391.0,0.0,1.0,74.0,1.0,0.0,"1,518",122.0,811,96.0,707,26.0,-,606,36.0,28,2.0,814,98.0,9.0,203.0,(2),Unreferred,external,no_fee,63.0,1.0,0.0,0.0,1.0,"80,000",1.0,1.0,0.0,0.0,0.0,0.000,482,418,1376.0,0.0,-,1.0,0.034044,0.0000,991,-,0.0,-,3.0
1,550392.0,0.0,1.0,64.0,0.0,0.0,"4,807",354.0,"1,052",82.0,"3,756",272.0,673,"3,164",456.0,"2,291",44.0,"1,265",116.0,0.0,0.0,15,In House,others,no_fee,203.0,1.0,0.0,0.0,1.0,"140,000",1.0,1.0,1.0,0.0,0.0,0.000,"2,165","2,165",1300.0,0.0,7,1.0,0.044086,0.0877,2,24,2.0,-,0.0
2,550393.0,0.0,1.0,75.0,1.0,0.0,"2,361",204.0,"1,351",118.0,"1,010",86.0,237,693,152.0,-,0.0,"1,623",166.0,9.0,18.0,(20),NaN,NaN,full_fee,201.0,1.0,0.0,0.0,1.0,"32,800",0.0,0.0,0.0,0.0,0.0,0.000,703,687,1376.0,0.0,-,1.0,0.039613,0.0000,"4,828",-,0.0,387,3.0
3,550394.0,0.0,2.0,73.0,0.0,1.0,"5,452",142.0,"1,195",50.0,"4,257",92.0,803,"1,618",64.0,"2,760",54.0,"1,605",54.0,9.0,23.0,30,NaN,NaN,full_fee,286.0,1.0,0.0,0.0,1.0,"100,000",1.0,0.0,0.0,0.0,0.0,0.000,"1,225","1,225",1372.0,1.0,493,1.0,0.001200,0.0000,"4,598",-,0.0,295,4.0
4,550395.0,0.0,2.0,68.0,0.0,0.0,170,34.0,88,20.0,82,14.0,10,10,4.0,-,0.0,66,18.0,0.0,0.0,(9),Affiliates,spillover,no_fee,123.0,1.0,0.0,0.0,1.0,"20,800",1.0,0.0,0.0,0.0,0.0,0.001,51,35,1338.0,0.0,-,2.0,0.003378,0.0168,"2,176","2,606",5.0,143,13.0

(19599, 50)

### Meanings of terms used

In [4]:
data_desc = pd.read_csv("./data/Data_Dictionary-06_11N.csv", encoding='cp1252')
term_desc = data_desc.iloc[:8]
term_desc

,Term,Description
0,Customer/CM,An individual who holds a XZVEE card
1,XZVEE Credit card company,A US based financial institution into credit and charge cards
2,Charge cards,Cards where the customer has to pay in full
3,Lending/Revolve cards,Credit cards where the customer has the option of partial payment
4,Prospects,An individual who doesn’t hold any XZVEE credit card
5,Spillover,A XZVEE CM taking another XZVEE card
6,Size of Wallet (SOW),External Credit Bureau variables
7,External cards,Non XZVEE Credit/Charge cards held by a person

### Description of variables

In [5]:
feature_desc = data_desc.iloc[11:]
feature_desc.columns = data_desc.iloc[10].values
feature_desc = feature_desc.reset_index(drop=True)
feature_desc

,Variable Name,Description
0,cust_max_credit_12m_amt,Maximum amount of single transaction made by customer in past 12 months
1,cust_max_remit_12m_amt,Maximum amount of single transaction payment made by customer in past 12 months
2,cnsumr_lend_tot_util_ratio,Total credit limit used off the assigned lending limit
3,sum_total_line_amt,Total credit limits of all cards with the customer
4,cust_id,XVZEE Customer ID
5,count_accts,Number of XZVEE accounts of the Customer
6,cm_age,Age of the Customer
7,flag_cust_fee_paid_6m,Flag if Customer has paid fee on any card in last 6 months
8,acq_sub_chn,Channel of acquisition of first the firt card of the customer
9,acq_type_grp,Customer type: Existing Customer or prospect
10,fee_type_grp,Fe type of the first card of the customer
11,Cust_tenure,Total Tenure of the cutomer with XZVEE in months
12,min_pay_ind,Flag to indicate if the customer has paid the minimum amount on the card ever in last 6 billing cycles
13,paid_in_full_ind,Flag to indicate if the customer has paid the total amount on any of the cards ever in last 6 billing cycles
14,referrals,Number of previous successful referrals made by customer in previous 5 years
15,spillover,Number of spillovers from the successful referrals
16,self_accts,No of cards when the customer self referred
17,Customer Low Quality indicator,Flag to identify if the customer is a low quality acquisition
18,cnsumr_chrg_actv_cust_cnt,Number of active charge card account of the customer
19,cnsumr_chrg_avg_credit_12m_amt,Average monthly spend on Charge cards
20,cnsumr_lend_actv_cust_cnt,Number of active lending card account of the customer
21,pre6m_cust_myca_active,Number of times the Customer logged into his online XZVEE account in last 6 months
22,pre6m_cust_mob_logins,Number of times the Customer logged into his online XZVEE account in last 6 months through mobile
23,direct_debit_ind,Flag to indicate if the customer has set up auto payment
24,cbr_3_score,External Bureau score of the customer
25,sow_revol_avg_paydown_pct,Size of Wallet: Total amount paid over revolving balance on external cards
26,sow_tot_annual_ext_pmt_amt,Size of Wallet: Average amount paid on external cards annually
27,sow_tot_revol_bal_amt,Size of Wallet: Total revolve balance on external cards
28,sow_tot_revol_cnt,Size of Wallet: Total external lending cards count
29,sow_tot_trans_bal_amt,Size of Wallet: Total balance amount on external cards
30,sow_tot_trans_cnt,Size of Wallet: Total external charge cards count
31,pre6m_total_mc_trs,Total profit made by XZVEE on the customer in last 6 months
32,cdss_most_rcnt_prob,Internal XZVEE risk score generated for the customer
33,flag_top_ed_spender,Flag to identify if the Customer is an everyday spender
34,pre6m_cust_spend,Total Spend in last 6 months
35,pre6m_cust_roc_cnt,Total number of transactions in last 6 months
36,pre6m_cust_non_disc_amt,Total Non discretionary spend in last 6 months
37,pre6m_cust_non_disc_cnt,Total Non discretionary transactions in last 6 months
38,pre6m_cust_disc_amt,Total discretionary spend in last 6 months
39,pre6m_cust_disc_cnt,Total discretionary transactions in last 6 months
40,pre6m_cust_outbound_amt,Total outbound spend in last 6 months
41,pre6m_cust_online_amt,Total online spend in last 6 months
42,pre6m_cust_online_cnt,Total online transactions in last 6 months
43,pre6m_cust_travel_amt,Total travel spend in last 6 months
44,pre6m_cust_travel_cnt,Total travel transactions in last 6 months
45,pre6m_cust_retail_amt,Total retail spend in last 6 months
46,pre6m_cust_retail_cnt,Total retail transactions in last 6 months
47,pre6m_spend_active_ind,Flag to indicate if the customer has spent on the cards in last 6 months
48,highly_utilized_ind,CM has spent >80% of the card limit in past 6 months om any of his cards

### Cleaning Data

In [6]:
def fix_column(df, x):
    reset_column = []
    for value in df[x]:
        try:
            value = float(value)
        except:
            value = (value.strip())
            value = (value.replace(",", ""))
            value = (value.replace("(", ""))
            value = (value.replace(")", ""))
        reset_column.append(value)
    df["{}_original".format(x)] = df[x]    
    df[x] = reset_column
    return df

In [7]:
df = pd.read_csv("./data/Training_Data_0611N.csv")

In [8]:
import numpy as np
df = df.replace(' -   ', np.nan)
df = df.dropna(subset=['cust_id'])
df.head()
df.shape

,cust_id,profitable_flag,count_accts,cm_age,flag_top_ed_spender,flag_cust_fee_paid_6m,pre6m_cust_spend,pre6m_cust_roc_cnt,pre6m_cust_non_disc_amt,pre6m_cust_non_disc_cnt,pre6m_cust_disc_amt,pre6m_cust_disc_cnt,pre6m_cust_outbound_amt,pre6m_cust_online_amt,pre6m_cust_online_cnt,pre6m_cust_travel_amt,pre6m_cust_travel_cnt,pre6m_cust_retail_amt,pre6m_cust_retail_cnt,pre6m_cust_myca_active,pre6m_cust_mob_logins,pre6m_total_mc_trs,acq_sub_chn,acq_type_grp,fee_type_grp,Cust_tenure,pre6m_spend_active_ind,highly_utilized_ind,min_pay_ind,paid_in_full_ind,sum_total_line_amt,direct_debit_ind,referrals,spillover,self_accts,Customer Low Quality indicator,cdss_most_rcnt_prob,cust_max_credit_12m_amt,cust_max_remit_12m_amt,cbr_3_score,cnsumr_chrg_actv_cust_cnt,cnsumr_chrg_avg_credit_12m_amt,cnsumr_lend_actv_cust_cnt,cnsumr_lend_tot_util_ratio,sow_revol_avg_paydown_pct,sow_tot_annual_ext_pmt_amt,sow_tot_revol_bal_amt,sow_tot_revol_cnt,sow_tot_trans_bal_amt,sow_tot_trans_cnt
0,550391.0,0.0,1.0,74.0,1.0,0.0,"1,518",122.0,811,96.0,707,26.0,NaN,606,36.0,28,2.0,814,98.0,9.0,203.0,(2),Unreferred,external,no_fee,63.0,1.0,0.0,0.0,1.0,"80,000",1.0,1.0,0.0,0.0,0.0,0.000,482,418,1376.0,0.0,NaN,1.0,0.034044,0.0000,991,NaN,0.0,NaN,3.0
1,550392.0,0.0,1.0,64.0,0.0,0.0,"4,807",354.0,"1,052",82.0,"3,756",272.0,673,"3,164",456.0,"2,291",44.0,"1,265",116.0,0.0,0.0,15,In House,others,no_fee,203.0,1.0,0.0,0.0,1.0,"140,000",1.0,1.0,1.0,0.0,0.0,0.000,"2,165","2,165",1300.0,0.0,7,1.0,0.044086,0.0877,2,24,2.0,NaN,0.0
2,550393.0,0.0,1.0,75.0,1.0,0.0,"2,361",204.0,"1,351",118.0,"1,010",86.0,237,693,152.0,NaN,0.0,"1,623",166.0,9.0,18.0,(20),NaN,NaN,full_fee,201.0,1.0,0.0,0.0,1.0,"32,800",0.0,0.0,0.0,0.0,0.0,0.000,703,687,1376.0,0.0,NaN,1.0,0.039613,0.0000,"4,828",NaN,0.0,387,3.0
3,550394.0,0.0,2.0,73.0,0.0,1.0,"5,452",142.0,"1,195",50.0,"4,257",92.0,803,"1,618",64.0,"2,760",54.0,"1,605",54.0,9.0,23.0,30,NaN,NaN,full_fee,286.0,1.0,0.0,0.0,1.0,"100,000",1.0,0.0,0.0,0.0,0.0,0.000,"1,225","1,225",1372.0,1.0,493,1.0,0.001200,0.0000,"4,598",NaN,0.0,295,4.0
4,550395.0,0.0,2.0,68.0,0.0,0.0,170,34.0,88,20.0,82,14.0,10,10,4.0,NaN,0.0,66,18.0,0.0,0.0,(9),Affiliates,spillover,no_fee,123.0,1.0,0.0,0.0,1.0,"20,800",1.0,0.0,0.0,0.0,0.0,0.001,51,35,1338.0,0.0,NaN,2.0,0.003378,0.0168,"2,176","2,606",5.0,143,13.0

(19595, 50)

In [9]:
df = fix_column(df, 'pre6m_cust_spend')
df = fix_column(df, 'pre6m_cust_non_disc_amt')
df = fix_column(df, 'pre6m_cust_disc_amt')
df = fix_column(df, 'pre6m_cust_outbound_amt')
df = fix_column(df, 'pre6m_cust_online_amt')
df = fix_column(df, 'pre6m_cust_travel_amt')
df = fix_column(df, 'pre6m_cust_retail_amt')
df = fix_column(df, 'pre6m_total_mc_trs')
df = fix_column(df, 'sum_total_line_amt')
df = fix_column(df, 'cust_max_credit_12m_amt')
df = fix_column(df, 'cust_max_remit_12m_amt')
df = fix_column(df, 'cnsumr_chrg_avg_credit_12m_amt')
df = fix_column(df, 'sow_tot_annual_ext_pmt_amt')
df = fix_column(df, 'sow_tot_revol_bal_amt')
df = fix_column(df, 'sow_tot_trans_bal_amt')

In [10]:
df['acq_sub_chn'] = df['acq_sub_chn'].astype('category') 
df['acq_type_grp'] = df['acq_type_grp'].astype('category') 
df['fee_type_grp'] = df['fee_type_grp'].astype('category')

In [11]:
df_cleaned = df[['cust_id', 'profitable_flag', 'count_accts', 'cm_age',
       'flag_top_ed_spender', 'flag_cust_fee_paid_6m', 'pre6m_cust_spend',
       'pre6m_cust_roc_cnt', 'pre6m_cust_non_disc_amt',
       'pre6m_cust_non_disc_cnt', 'pre6m_cust_disc_amt', 'pre6m_cust_disc_cnt',
       'pre6m_cust_outbound_amt', 'pre6m_cust_online_amt',
       'pre6m_cust_online_cnt', 'pre6m_cust_travel_amt',
       'pre6m_cust_travel_cnt', 'pre6m_cust_retail_amt',
       'pre6m_cust_retail_cnt', 'pre6m_cust_myca_active',
       'pre6m_cust_mob_logins', 'pre6m_total_mc_trs', 'acq_sub_chn',
       'acq_type_grp', 'fee_type_grp', 'Cust_tenure', 'pre6m_spend_active_ind',
       'highly_utilized_ind', 'min_pay_ind', 'paid_in_full_ind',
       'sum_total_line_amt', 'direct_debit_ind', 'referrals', 'spillover',
       'self_accts', 'Customer Low Quality indicator', 'cdss_most_rcnt_prob',
       'cust_max_credit_12m_amt', 'cust_max_remit_12m_amt', 'cbr_3_score',
       'cnsumr_chrg_actv_cust_cnt', 'cnsumr_chrg_avg_credit_12m_amt',
       'cnsumr_lend_actv_cust_cnt', 'cnsumr_lend_tot_util_ratio',
       'sow_revol_avg_paydown_pct', 'sow_tot_annual_ext_pmt_amt',
       'sow_tot_revol_bal_amt', 'sow_tot_revol_cnt', 'sow_tot_trans_bal_amt',
       'sow_tot_trans_cnt']]

In [12]:
df_cleaned.head()
df_cleaned.shape

,cust_id,profitable_flag,count_accts,cm_age,flag_top_ed_spender,flag_cust_fee_paid_6m,pre6m_cust_spend,pre6m_cust_roc_cnt,pre6m_cust_non_disc_amt,pre6m_cust_non_disc_cnt,pre6m_cust_disc_amt,pre6m_cust_disc_cnt,pre6m_cust_outbound_amt,pre6m_cust_online_amt,pre6m_cust_online_cnt,pre6m_cust_travel_amt,pre6m_cust_travel_cnt,pre6m_cust_retail_amt,pre6m_cust_retail_cnt,pre6m_cust_myca_active,pre6m_cust_mob_logins,pre6m_total_mc_trs,acq_sub_chn,acq_type_grp,fee_type_grp,Cust_tenure,pre6m_spend_active_ind,highly_utilized_ind,min_pay_ind,paid_in_full_ind,sum_total_line_amt,direct_debit_ind,referrals,spillover,self_accts,Customer Low Quality indicator,cdss_most_rcnt_prob,cust_max_credit_12m_amt,cust_max_remit_12m_amt,cbr_3_score,cnsumr_chrg_actv_cust_cnt,cnsumr_chrg_avg_credit_12m_amt,cnsumr_lend_actv_cust_cnt,cnsumr_lend_tot_util_ratio,sow_revol_avg_paydown_pct,sow_tot_annual_ext_pmt_amt,sow_tot_revol_bal_amt,sow_tot_revol_cnt,sow_tot_trans_bal_amt,sow_tot_trans_cnt
0,550391.0,0.0,1.0,74.0,1.0,0.0,1518,122.0,811,96.0,707,26.0,NaN,606,36.0,28,2.0,814,98.0,9.0,203.0,2,Unreferred,external,no_fee,63.0,1.0,0.0,0.0,1.0,80000,1.0,1.0,0.0,0.0,0.0,0.000,482,418,1376.0,0.0,NaN,1.0,0.034044,0.0000,991,NaN,0.0,NaN,3.0
1,550392.0,0.0,1.0,64.0,0.0,0.0,4807,354.0,1052,82.0,3756,272.0,673,3164,456.0,2291,44.0,1265,116.0,0.0,0.0,15,In House,others,no_fee,203.0,1.0,0.0,0.0,1.0,140000,1.0,1.0,1.0,0.0,0.0,0.000,2165,2165,1300.0,0.0,7,1.0,0.044086,0.0877,2,24,2.0,NaN,0.0
2,550393.0,0.0,1.0,75.0,1.0,0.0,2361,204.0,1351,118.0,1010,86.0,237,693,152.0,NaN,0.0,1623,166.0,9.0,18.0,20,NaN,NaN,full_fee,201.0,1.0,0.0,0.0,1.0,32800,0.0,0.0,0.0,0.0,0.0,0.000,703,687,1376.0,0.0,NaN,1.0,0.039613,0.0000,4828,NaN,0.0,387,3.0
3,550394.0,0.0,2.0,73.0,0.0,1.0,5452,142.0,1195,50.0,4257,92.0,803,1618,64.0,2760,54.0,1605,54.0,9.0,23.0,30,NaN,NaN,full_fee,286.0,1.0,0.0,0.0,1.0,100000,1.0,0.0,0.0,0.0,0.0,0.000,1225,1225,1372.0,1.0,493,1.0,0.001200,0.0000,4598,NaN,0.0,295,4.0
4,550395.0,0.0,2.0,68.0,0.0,0.0,170,34.0,88,20.0,82,14.0,10,10,4.0,NaN,0.0,66,18.0,0.0,0.0,9,Affiliates,spillover,no_fee,123.0,1.0,0.0,0.0,1.0,20800,1.0,0.0,0.0,0.0,0.0,0.001,51,35,1338.0,0.0,NaN,2.0,0.003378,0.0168,2176,2606,5.0,143,13.0

(19595, 50)

In [14]:
df_cleaned.to_csv('./data/Training_Data_0611N_cleaned.csv', index=False)

### Cleaning test data

In [15]:
df = pd.read_csv('./data/Evaluation_Data_0611_Nv.csv')
df.head()

,cust_id,count_accts,cm_age,flag_top_ed_spender,flag_cust_fee_paid_6m,pre6m_cust_spend,pre6m_cust_roc_cnt,pre6m_cust_non_disc_amt,pre6m_cust_non_disc_cnt,pre6m_cust_disc_amt,pre6m_cust_disc_cnt,pre6m_cust_outbound_amt,pre6m_cust_online_amt,pre6m_cust_online_cnt,pre6m_cust_travel_amt,pre6m_cust_travel_cnt,pre6m_cust_retail_amt,pre6m_cust_retail_cnt,pre6m_cust_myca_active,pre6m_cust_mob_logins,pre6m_total_mc_trs,acq_sub_chn,acq_type_grp,fee_type_grp,Cust_tenure,pre6m_spend_active_ind,highly_utilized_ind,min_pay_ind,paid_in_full_ind,sum_total_line_amt,direct_debit_ind,referrals,spillover,self_accts,Customer Low Quality indicator,cdss_most_rcnt_prob,cust_max_credit_12m_amt,cust_max_remit_12m_amt,cbr_3_score,cnsumr_chrg_actv_cust_cnt,cnsumr_chrg_avg_credit_12m_amt,cnsumr_lend_actv_cust_cnt,cnsumr_lend_tot_util_ratio,sow_revol_avg_paydown_pct,sow_tot_annual_ext_pmt_amt,sow_tot_revol_bal_amt,sow_tot_revol_cnt,sow_tot_trans_bal_amt,sow_tot_trans_cnt
0,569986,1,37,0.0,0,"9,868",760,777,174,"9,091",586,"1,705","2,286",280,"3,219",268,"2,668",240,5,9,474,Paid Search,external,no_fee,10.0,1.0,1.0,0.0,0.0,"46,000",0.0,0.0,0.0,0.0,0.0,0.048,"1,880","1,875",833.0,0.0,-,1.0,1.055513,0.0,-,-,0.0,-,0.0
1,569987,2,33,0.0,0,-,0,-,0,-,0,-,-,0,-,0,-,0,0,0,(0),MGM,external,reduced_fee,1.0,0.0,0.0,0.0,0.0,"5,133",0.0,0.0,0.0,0.0,0.0,NaN,-,-,NaN,NaN,-,NaN,NaN,NaN,-,-,NaN,-,NaN
2,569988,2,40,1.0,0,"2,401",302,"1,045",166,"1,357",136,289,483,96,220,18,986,176,5,5,2,MGM,spillover,no_fee,10.0,1.0,0.0,0.0,1.0,"69,600",0.0,0.0,0.0,0.0,0.0,0.000,739,618,1251.0,0.0,43,2.0,0.029297,0.0,-,-,0.0,-,0.0
3,569989,1,34,1.0,1,"9,836",856,829,190,"9,007",666,"2,104","2,545",292,"2,109",254,"1,921",274,6,20,170,MGM,external,reduced_fee,14.0,1.0,0.0,0.0,0.0,-,1.0,0.0,0.0,0.0,0.0,0.000,"1,864","1,851",1004.0,1.0,829,0.0,0.000000,0.0,-,-,0.0,-,0.0
4,569990,1,28,0.0,0,"2,351",260,584,90,"1,767",170,63,282,56,127,26,"1,878",124,3,3,(9),MGM,external,no_fee,7.0,1.0,0.0,0.0,1.0,"9,600",0.0,0.0,0.0,0.0,0.0,0.000,752,731,1293.0,0.0,-,1.0,0.200658,0.0,-,-,0.0,-,0.0

In [16]:
def fix_column(df, x):
    reset_column = []
    for value in df[x]:
        try:
            value = float(value)
        except:
            value = (value.strip())
            value = (value.replace(",", ""))
            value = (value.replace("(", ""))
            value = (value.replace(")", ""))
        reset_column.append(value)
    df["{}_original".format(x)] = df[x]    
    df[x] = reset_column
    return df

In [17]:
import numpy as np
df = df.replace(' -   ', np.nan)
df = df.dropna(subset=['cust_id'])
df.head()
df.shape

,cust_id,count_accts,cm_age,flag_top_ed_spender,flag_cust_fee_paid_6m,pre6m_cust_spend,pre6m_cust_roc_cnt,pre6m_cust_non_disc_amt,pre6m_cust_non_disc_cnt,pre6m_cust_disc_amt,pre6m_cust_disc_cnt,pre6m_cust_outbound_amt,pre6m_cust_online_amt,pre6m_cust_online_cnt,pre6m_cust_travel_amt,pre6m_cust_travel_cnt,pre6m_cust_retail_amt,pre6m_cust_retail_cnt,pre6m_cust_myca_active,pre6m_cust_mob_logins,pre6m_total_mc_trs,acq_sub_chn,acq_type_grp,fee_type_grp,Cust_tenure,pre6m_spend_active_ind,highly_utilized_ind,min_pay_ind,paid_in_full_ind,sum_total_line_amt,direct_debit_ind,referrals,spillover,self_accts,Customer Low Quality indicator,cdss_most_rcnt_prob,cust_max_credit_12m_amt,cust_max_remit_12m_amt,cbr_3_score,cnsumr_chrg_actv_cust_cnt,cnsumr_chrg_avg_credit_12m_amt,cnsumr_lend_actv_cust_cnt,cnsumr_lend_tot_util_ratio,sow_revol_avg_paydown_pct,sow_tot_annual_ext_pmt_amt,sow_tot_revol_bal_amt,sow_tot_revol_cnt,sow_tot_trans_bal_amt,sow_tot_trans_cnt
0,569986,1,37,0.0,0,"9,868",760,777,174,"9,091",586,"1,705","2,286",280,"3,219",268,"2,668",240,5,9,474,Paid Search,external,no_fee,10.0,1.0,1.0,0.0,0.0,"46,000",0.0,0.0,0.0,0.0,0.0,0.048,"1,880","1,875",833.0,0.0,NaN,1.0,1.055513,0.0,NaN,NaN,0.0,NaN,0.0
1,569987,2,33,0.0,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,0,0,(0),MGM,external,reduced_fee,1.0,0.0,0.0,0.0,0.0,"5,133",0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,569988,2,40,1.0,0,"2,401",302,"1,045",166,"1,357",136,289,483,96,220,18,986,176,5,5,2,MGM,spillover,no_fee,10.0,1.0,0.0,0.0,1.0,"69,600",0.0,0.0,0.0,0.0,0.0,0.000,739,618,1251.0,0.0,43,2.0,0.029297,0.0,NaN,NaN,0.0,NaN,0.0
3,569989,1,34,1.0,1,"9,836",856,829,190,"9,007",666,"2,104","2,545",292,"2,109",254,"1,921",274,6,20,170,MGM,external,reduced_fee,14.0,1.0,0.0,0.0,0.0,NaN,1.0,0.0,0.0,0.0,0.0,0.000,"1,864","1,851",1004.0,1.0,829,0.0,0.000000,0.0,NaN,NaN,0.0,NaN,0.0
4,569990,1,28,0.0,0,"2,351",260,584,90,"1,767",170,63,282,56,127,26,"1,878",124,3,3,(9),MGM,external,no_fee,7.0,1.0,0.0,0.0,1.0,"9,600",0.0,0.0,0.0,0.0,0.0,0.000,752,731,1293.0,0.0,NaN,1.0,0.200658,0.0,NaN,NaN,0.0,NaN,0.0

(5000, 49)

In [18]:
df = fix_column(df, 'pre6m_cust_spend')
df = fix_column(df, 'pre6m_cust_non_disc_amt')
df = fix_column(df, 'pre6m_cust_disc_amt')
df = fix_column(df, 'pre6m_cust_outbound_amt')
df = fix_column(df, 'pre6m_cust_online_amt')
df = fix_column(df, 'pre6m_cust_travel_amt')
df = fix_column(df, 'pre6m_cust_retail_amt')
df = fix_column(df, 'pre6m_total_mc_trs')
df = fix_column(df, 'sum_total_line_amt')
df = fix_column(df, 'cust_max_credit_12m_amt')
df = fix_column(df, 'cust_max_remit_12m_amt')
df = fix_column(df, 'cnsumr_chrg_avg_credit_12m_amt')
df = fix_column(df, 'sow_tot_annual_ext_pmt_amt')
df = fix_column(df, 'sow_tot_revol_bal_amt')
df = fix_column(df, 'sow_tot_trans_bal_amt')

In [19]:
df['acq_sub_chn'] = df['acq_sub_chn'].astype('category') 
df['acq_type_grp'] = df['acq_type_grp'].astype('category') 
df['fee_type_grp'] = df['fee_type_grp'].astype('category')

In [20]:
df_cleaned = df[['cust_id', 'count_accts', 'cm_age',
       'flag_top_ed_spender', 'flag_cust_fee_paid_6m', 'pre6m_cust_spend',
       'pre6m_cust_roc_cnt', 'pre6m_cust_non_disc_amt',
       'pre6m_cust_non_disc_cnt', 'pre6m_cust_disc_amt', 'pre6m_cust_disc_cnt',
       'pre6m_cust_outbound_amt', 'pre6m_cust_online_amt',
       'pre6m_cust_online_cnt', 'pre6m_cust_travel_amt',
       'pre6m_cust_travel_cnt', 'pre6m_cust_retail_amt',
       'pre6m_cust_retail_cnt', 'pre6m_cust_myca_active',
       'pre6m_cust_mob_logins', 'pre6m_total_mc_trs', 'acq_sub_chn',
       'acq_type_grp', 'fee_type_grp', 'Cust_tenure', 'pre6m_spend_active_ind',
       'highly_utilized_ind', 'min_pay_ind', 'paid_in_full_ind',
       'sum_total_line_amt', 'direct_debit_ind', 'referrals', 'spillover',
       'self_accts', 'Customer Low Quality indicator', 'cdss_most_rcnt_prob',
       'cust_max_credit_12m_amt', 'cust_max_remit_12m_amt', 'cbr_3_score',
       'cnsumr_chrg_actv_cust_cnt', 'cnsumr_chrg_avg_credit_12m_amt',
       'cnsumr_lend_actv_cust_cnt', 'cnsumr_lend_tot_util_ratio',
       'sow_revol_avg_paydown_pct', 'sow_tot_annual_ext_pmt_amt',
       'sow_tot_revol_bal_amt', 'sow_tot_revol_cnt', 'sow_tot_trans_bal_amt',
       'sow_tot_trans_cnt']]

In [21]:
df_cleaned.to_csv('./data/Evaluation_Data_0611_Nv_cleaned.csv', index=False)